name: ClashX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: xcode-27
    env:
      MIHOMO_TAG: v1.19.30
      GH_TOKEN: ${{ github.token }}

    steps:

    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: build infos
      run: |
        /usr/libexec/PlistBuddy -c "Set CFBundleVersion $(git rev-list --count HEAD)" ClashX/Info.plist
        /usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $(git describe --tags --abbrev=0 2>/dev/null || echo '1.0.0')" ClashX/Info.plist
        /usr/libexec/PlistBuddy -c "Add coreVersion string $(ls clash.meta | grep -m1 "" | sed -ne 's/.*64-\(.*\).gz/\1/p')" ClashX/Info.plist
        /usr/libexec/PlistBuddy -c "Add buildTime string $(date +%Y-%m-%d\ %H:%M)" ClashX/Info.plist

    - name: install deps
      run: |
        bash install_dependency.sh "$MIHOMO_TAG"
        xcodebuild -resolvePackageDependencies -project ClashX.xcodeproj

    - name: build (unsigned)
      run: |
        xcodebuild archive \
          -project ClashX.xcodeproj \
          -scheme "ClashX Meta" \
          -archivePath archive/ClashX.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: create zip
      run: ditto -c -k --sequesterRsrc --keepParent archive/ClashX.xcarchive/Products/Applications/ClashX\ Meta.app "ClashX Meta.zip"

    - name: upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "ClashX-Meta-unsigned"
        path: "ClashX Meta.zip"
